config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root controller: :rooms, action: :index
  resources :room_messages
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord

	has_many :room_messages, dependent: :destroy,
                         inverse_of: :room

                         
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
belongs_to :room, inverse_of: :room_messages

def as_json(options)
  super(options).merge(user_avatar_url: user.gravatar_url)
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def gravatar_url
	  gravatar_id = Digest::MD5::hexdigest(email).downcase
	  "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# forcé l'utilisateur a s'inscrire d"abord
	 before_action :authenticate_user!

	 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
	 before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)
  RoomChannel.broadcast_to @room, @room_message
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  before_action :load_entities

  def index
    @rooms = Room.all
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end
  def new
    @room = Room.new
  end

  def create
    @room = Room.new permitted_parameters

    if @room.save
      flash[:success] = "Welam #{@room.name} crée avec success"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Welam #{@room.name} mise a jour avec success"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_url(user)
	  gravatar_id = Digest::MD5::hexdigest(user.email).downcase
	  url = "https://gravatar.com/avatar/#{gravatar_id}.png"
	end
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WelamApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Links Top/!-->
    <%= render "shared/links/links-top" %>
  </head>

  <body>
   <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: 'shared/nav/navbar' %>
          <div class="my-3">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Publiez", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Créez un Welam
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-columnalert alert-primary alert-heading">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
       <hr />
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
  Vous n'avez encore crée de Welam
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>
  Modifiez <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Bienvenu Sur WelamApp
      </h4>

      <p>
        Nous vous Aidons a mettre la joie dans votre journée.
      </p>

      <hr />

      <p>
        Vous pouvez créer un Welam sur la bar droite.
      </p>
    </div>
</div>

app/views/rooms/new.html.erb
<h1>
  Créez un Welam 
</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
</div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Envoi", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>


<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/links/_links-top.html.erb
<%= javascript_pack_tag 'application' %>
<%= stylesheet_pack_tag 'application' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/nav/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href="#">WelamApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= current_user.gravatar_url %>">
        <%= current_user.username %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>
</nav>